name = "StrucPopNe"
uuid = "dcbe1a3e-d647-46a3-bd37-f2428940af3e"
authors = ["Alan R. Rogers <rogers@anthro.utah.edu>"]
version = "0.1.0"

[deps]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
